[workspace]
resolver = "2"
members = ["crates/server", "crates/trtcp"]

[workspace.dependencies]
tokio = { version = "1.43.0", features = ["full", "default"] }
thiserror = { version = "2.0.11" }
getset = { version = "0.1.4" }
