[package]
name = "camelot"
version = "1.0.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
tokio = { workspace = true }
trtcp = { path = "../trtcp" }
thiserror = { workspace = true }